name: Mid_Astha
 
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
 
jobs:
  build:
    runs-on: ubuntu-latest
 
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
 
      - name: Set up .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.x'
 
      - name: Restore dependencies
        run: dotnet restore ./Mid_HelloWorld.csproj
 
      - name: Build application
        run: dotnet build ./Mid_HelloWorld.csproj --no-restore --configuration Release
 
  test:
    runs-on: ubuntu-latest
 
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
 
      - name: Set up .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.x'
 
      - name: Run tests
        run: |
          dotnet test ./Mid_HelloWorld.csproj --no-build
